### PR TITLE
Refactor context -> canvasContext

### LINKED ISSUE #46: Error since 2.1.2 (this.context.measureText is not a function)
Hello, 
Since i upgrade from 2.1.1 to 2.1.2, i have this error:

```
TypeError: this.context.measureText is not a function
Trace de la pile :
measureWidth@http://localhost:3000/app/vendor.js:12612:20
getLines@http://localhost:3000/app/vendor.js:12653:21
render@http://localhost:3000/app/vendor.js:12766:28
...
```

Do you know the problem ?

Thank you

### PR DESCRIPTION
**Pull request by joelmukuthu**
Since 'context' is a property used by React

Fixes #46

### CODE REVIEW

**Comment by PabloSichert** [comment]
Whoopsie :D Thanks!
