### ISSUE TITLE
Error since 2.1.2 (this.context.measureText is not a function)

### ISSUE THREAD

**Issue by damien916** [One-com/react-truncate#46]
Hello, 
Since i upgrade from 2.1.1 to 2.1.2, i have this error:

```
TypeError: this.context.measureText is not a function
Trace de la pile :
measureWidth@http://localhost:3000/app/vendor.js:12612:20
getLines@http://localhost:3000/app/vendor.js:12653:21
render@http://localhost:3000/app/vendor.js:12766:28
...
```

Do you know the problem ?

Thank you

**Comment by koox00** [comment]
I've got the same error.

```
Truncate.CommonJS.js:184 Uncaught TypeError: this.context.measureText is not a function
    at Truncate.measureWidth (Truncate.CommonJS.js:184)
    at Truncate.getLines (Truncate.CommonJS.js:225)
    at Truncate.render (Truncate.CommonJS.js:338)
```

**Comment by indapublic** [comment]
+1

**Comment by PabloSichert** [comment]
Thanks for reporting!

Out on npm with [`v2.1.4`](https://github.com/One-com/react-truncate/releases/tag/v2.1.4).

**Comment by damien916** [comment]
Thanks you so much, you're so fast 👍
