### ISSUE TITLE
Isn't working with react 16.2

### ISSUE THREAD

**Issue by barmaglot92** [One-com/react-truncate#87]
Hi, Do you sure that this lib works with react 16?
I'v got error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: ob
ject.
    in TextCollapse
    in div
    in section
    in Snippet
    in section
    in AdvComposer
    in div
    in MoviePage
    in Connect(MoviePage)
    in div
    in div
    in div
    in Page                                                                                                                                                in App
    in Connect(App)
    in Provider
  kp-touch:utils-render:error TypeError: element.type.toLowerCase is not a function
```
if using <ReactTruncate>
